default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: e_arca_api_development

test:
  <<: *default
  database: e_arca_api_test

production:
  <<: *default
  database: e_arca_api_production
  username: e_arca_api
  password: <%= ENV["E_ARCA_API_DATABASE_PASSWORD"] %>
