local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

cloudflare_documents:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:cloudflare_documents, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:cloudflare_documents, :secret_access_key) %>
  region: auto
  bucket: <%= Rails.application.credentials.dig(:cloudflare_documents, :bucket) %>
  endpoint: https://<%= Rails.application.credentials.dig(:cloudflare_documents, :account_id) %>.r2.cloudflarestorage.com
  force_path_style: true
